version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  my-network: